spring:
  datasource:
    url: jdbc:mysql://localhost:3306/competition?serverTimezone=GMT&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
